package ClashRoyale.model.elements;

public enum CellValue {

    GRASS, WATER,

    // towers
    KING_TOWER,  DYING_KING_TOWER,  ENEMY_KING_TOWER,
    QUEEN_TOWER, DYING_QUEEN_TOWER, ENEMY_QUEEN_TOWER,

    // troops
    BARBARIAN, DYING_BARBARIAN, ENEMY_BARBARIAN,
    ARCHER,    DYING_ARCHER,    ENEMY_ARCHER,
    DRAGON,    DYING_DRAGON,    ENEMY_DRAGON,
    WIZARD,    DYING_WIZARD,    ENEMY_WIZARD,
    PEKKA,     DYING_PEKKA,     ENEMY_PEKKA,
    GIANT,     DYING_GIANT,     ENEMY_GIANT,
    VALKYRIE,  DYING_VALKYRIE,  ENEMY_VALKYRIE,

    // spells
    FIREBALL, ARROWS, RAGE,

    // buildings
    CANNON, DYING_CANNON,
    INFERNO_TOWER, DYING_INFERNO_TOWER,

}
